exception File_not_found of string
exception Invalid_rubric of string
val expected_version : string
val email_subject : string
val email_admins : string
val cms_dir : string
val cms_fname : string
val depend_file : string
val diff_results : string
val email_dir : string
val lib_file : string
val nocompile_dir : string
val opam_packages_file : string
val output_dir : string
val reverse_cms : string
val reverse_dir : string
val reverse_rubric : string
val rubric_file : string
val smoke_targets : string
val std_opam_packages : string list
val tests_dir : string
val test_output : string
val fail_output : string
