open Core.Std

(** [run file args] run the executable generated by [cs3110 compile file] *)
let run (main_module : string) (args : string list) : int =
  let main_module = Filepath_util.strip_suffix main_module in
  let build_dir = "_build" in (* TODO abstract with config-file *)
  let cmd = Format.sprintf "%s/%s.d.byte" build_dir main_module in
  let () = Filepath_util.assert_file_exists cmd in
  Process_util.run_process cmd args

let command =
  Command.basic
    ~summary:"Runs a compiled executable."
    ~readme:(fun () -> String.concat ~sep:"\n" [
      "The run command runs a compiled executable.";
      "Compile with the compile command, then run."
    ])
    Command.Spec.(
      empty
      +> flag ~aliases:["-r"] "-recompile" no_arg ~doc:" Compile target before running"
      +> anon ("target" %: string)
      +> anon (sequence ("args" %: string))
    )
    (fun recompile main args () ->
      (* TODO uncomment after merging cli-compile *)
      (* let () = if recompile then Command.compile main in *)
      Process_util.check_code (run main args))
