(** [run file args] run the executable generated by [cs3110 compile file] *)
let run (main_module : string) (args : string list) : int =
  let cmd = Format.sprintf "_build/%s.d.byte" main_module in
  let () = Filepath_util.assert_file_exists cmd in
  Process_util.run_process cmd args

